# Generated by Django 3.1 on 2020-11-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0017_update_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vminterface',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]

