# Generated by Django 3.1 on 2020-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0116_rearport_max_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]

